GET http://localhost:3000/api/products

###

GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/register
Content-Type: application/json

{
    "email": "jesmine@mejl.se",
    "name": "jesmine",
    "password": "123"
}